import { Nft } from './types'

const Nfts: Nft[] = [
  {
    name: 'Jackie',
    description: 'The king of Pop! He is very happy to be into your wallet and is singing you "Smooth Criminal" every day, forever.',
    images: {
      lg: 'jackson.jpeg',
      md: 'jackson.jpeg',
      sm: 'jackson.jpeg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmRFB5fSLQCfPsWvhJ5wZNpZwJRrypaLpJ3AQAYgPyRtGH',
    },
    sortOrder: 999,
    bunnyId: 11,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Diego',
    description: "Oopsie daisy! Maradona's had a bit of an accident. Poor little fella.",
    images: {
      lg: 'maradona.jpeg',
      md: 'maradona.jpeg',
      sm: 'maradona.jpeg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmRVCZWmB1RMU83JZ4ttzjfd94GQmR3PyRxrYsRpAztM4K',
    },
    sortOrder: 999,
    bunnyId: 10,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Karl',
    description: 'Aww, looks like give eating to Choupette all day is tough work. Sweet dreams!',
    images: {
      lg: 'karl.jpeg',
      md: 'karl.jpeg',
      sm: 'karl.jpeg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmSybMhxFaCTdxUu6Aq51V6f4Qk1MRFdkP1e88o7w5XhA6',
      blur: 'karl.jpeg',
    },
    sortOrder: 999,
    bunnyId: 5,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Albert',
    description: 'Albert is always cheerful when there are masses around. Smile!',
    images: {
      lg: 'einstein.jpg',
      md: 'einstein.jpg',
      sm: 'einstein.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmXLMgXbKTxmq1DyWVNAU2C2g6NiKechzSqCDjoszADyF9',
      blur: 'einstein.jpg',
    },
    sortOrder: 999,
    bunnyId: 9,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Marilyn',
    description: "Don't let that Marilyn smile deceive you... She's a master barbituric chef!",
    images: {
      lg: 'marilyn.jpg',
      md: 'marilyn.jpg',
      sm: 'marilyn.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmTj8wLhiNUQ5zp2deGqWkb1e47gvvS9ujNYrxzTGayFxf',
      blur: 'marilyn.jpg',
    },
    sortOrder: 999,
    bunnyId: 8,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Adolfo',
    description: "Nommm... Oh hi, I'm just meditating on the meaning of life.",
    images: {
      lg: 'adolfo.jpg',
      md: 'adolfo.jpg',
      sm: 'adolfo.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmeL3psTEzfaiChvDv4tcqxM3G2GZWiXnrW2sgQYr8y2Kg',
      blur: 'adolfo.jpg',
    },
    sortOrder: 999,
    bunnyId: 6,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Charlie',
    description: "Three guesses what's put that twinkle in those eyes! (Hint: it's Christmas carol)",
    images: {
      lg: 'charlie.jpg',
      md: 'charlie.jpg',
      sm: 'charlie.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmZmWfRrTu5vM8t2mm2GHbCNYzxPc1dLwHd1GWvCjxN6pW',
      blur: 'charlie.jpg',
    },
    sortOrder: 999,
    bunnyId: 7,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Kobe',
    description: 'He love nothing more than swapping elicopters. Especially on BSC.',
    images: {
      lg: 'kobe.jpg',
      md: 'kobe.jpg',
      sm: 'kobe.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmNMjcdPkVvKYrXSEY4Jy7c9Fm9sv5DTzX8crkQquuapt9',
      blur: 'kobe.jpg',
    },
    sortOrder: 999,
    bunnyId: 0,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Johnny',
    description: "It's raining on this doll, but he doesn't seem to mind, he is thinking of Yoko. Can you blame him?",
    images: {
      lg: 'johnny.jpg',
      md: 'johnny.jpg',
      sm: 'johnny.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmUJNnfnxRavrSFKdKGK8TpgSf9qAAWAEJvy5RhYkPBLWg',
      blur: 'johnny.jpg',
    },
    sortOrder: 999,
    bunnyId: 1,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Kurt',
    description: "This doll likes their white powder. What's your favorite topping?",
    images: {
      lg: 'Kurt.jpg',
      md: 'Kurt.jpg',
      sm: 'Kurt.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmaJZVzpp7tbtaG6fLGbgJLQ4HNtUymzTz2fAg2t1eMCF4',
      blur: 'Kurt.jpg',
    },
    sortOrder: 999,
    bunnyId: 2,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'My Lady',
    description: "Love makes the world go 'round... And this dolls knows it.",
    images: {
      lg: 'mylady.jpg',
      md: 'mylady.jpg',
      sm: 'mylady.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmS5gm1c9MAwtoc9YpyJzTU6CJveGTwkwHELQAD7bSsBHY',
      blur: 'mylady.jpg',
    },
    sortOrder: 999,
    bunnyId: 3,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Jimmy',
    description: 'This doll has something blue on their body! They really loves it.',
    images: {
      lg: 'jimmy.jpg',
      md: 'jimmy.jpg',
      sm: 'jimmy.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmSdcJNJuehZrPjfaXZFbLx3P8V18i65oZt1p769t2HCKC',
      blur: 'jimmy.jpg',
    },
    sortOrder: 999,
    bunnyId: 4,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Pelvis',
    description: 'He is singing Blue Eyes Crying in the Rain, while taking barbiturates.',
    images: {
      lg: 'pelvis.jpeg',
      md: 'pelvis.jpeg',
      sm: 'pelvis.jpeg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmWD8CL6d2GFv8EcDpC6qmy8TC7qT1ZSm8x2VM6ZCN3hD7',
      blur: 'pelvis.jpeg',
    },
    sortOrder: 999,
    bunnyId: 12,
    lastBid: 0,
    lastPrice: 0,
  },
  {
    name: 'Stepho',
    description: 'AAAAAAA.',
    images: {
      lg: 'stepho.jpg',
      md: 'stepho.jpg',
      sm: 'stepho.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmcKWtMP6SbqhTZC8wpwNCdMNbnXoai8tQ7VSyH1SRYmM3',
      blur: 'stepho.jpg',
    },
    sortOrder: 999,
    bunnyId: 13,
    lastBid: 0,
    lastPrice: 0,
  },
]

export default Nfts
